# Generated by Django 4.1 on 2022-11-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0007_alter_pet_breed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                ("results", models.TextField(max_length=500)),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.pet",
                    ),
                ),
            ],
        ),
    ]
