# Generated by Django 4.1 on 2022-11-14 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_pet_breed"),
        ("staff", "0006_alter_appointment_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 15, 0, 43, 18, 326640)
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="accounts.pet",
            ),
        ),
    ]
