# Generated by Django 4.1 on 2022-11-20 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0012_remove_appointment_multiple_hour_slot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 20, 2, 38, 27, 844264)
            ),
        ),
    ]
