# Generated by Django 4.1 on 2022-11-20 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0013_alter_appointment_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 20, 4, 50, 28, 299564)
            ),
        ),
    ]
