# Generated by Django 4.1 on 2022-10-15 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
