# Generated by Django 4.1 on 2022-10-17 11:33

import accounts.models
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userprofile_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                    accounts.models.is_number,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="IL", unique=True
            ),
        ),
    ]
