# Generated by Django 4.1 on 2022-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_pet_breed_alter_pet_owner_delete_breed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
