# Generated by Django 4.1 on 2022-11-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_pet_breed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=9000, max_digits=7),
        ),
        migrations.AlterField(
            model_name="vet",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=14000, max_digits=7),
        ),
    ]
