# Generated by Django 4.1 on 2022-12-21 16:42

import accounts.models
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_assistant_salary_alter_vet_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.CharField(
                max_length=9,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.MaxLengthValidator(9),
                    accounts.models.is_number,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region="IL", unique=True
            ),
        ),
    ]
